openapi: 3.0.2
servers:
  - description: project_review localhost API document
    url: http://localhost:8000
info:
  version: "1.0.0"
  title: project_review-API
  description: The API for project_review
  contact:
    name: Inchan Song
    url: https://github.com/inchanS
    email: song@inchan.dev
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
paths:
  /users/signup:
    $ref: "./user/signUp.yaml"
  /users/signin:
    $ref: "./user/signIn.yaml"
  /users/checknickname:
    $ref: "./user/checkNickname.yaml"
  /users/checkemail:
    $ref: "./user/checkEmail.yaml"
  /users/getme:
    $ref: "./user/getMe.yaml"
  /comments:
    $ref: "./comment/index.yaml"
  /comments/{feedId}:
    $ref: "./comment/getComment.yaml"
  /comments/{commentId}:
    $ref: "./comment/deleteComment.yaml"