openapi: 3.0.2
servers:
  - description: project_review localhost API document
    url: http://localhost:8000
  - description: project_review AWS RDS Test API document
    url: http://15.164.86.242:8005
info:
  version: "1.0.0"
  title: project_review-API
  description: The API for project_review
  contact:
    name: Inchan Song
    url: https://github.com/inchanS
    email: song@inchan.dev
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
paths:
  /users/signup:
    $ref: "./user/signUp.yaml"
  /users/checknickname:
    $ref: "./user/checkNickname.yaml"
  /users/checkemail:
    $ref: "./user/checkEmail.yaml"
  /users/signin:
    $ref: "./user/signIn.yaml"
  /users/userinfo:
    $ref: "./user/userInfo.yaml"
  /users/userinfo/{userId}:
    $ref: "./user/getUserInfo.yaml"

  /comments:
    $ref: "./comment/createAndUpdate.yaml"
  /comments/{feedId}:
    $ref: "./comment/getComment.yaml"
  /comments/{commentId}:
    $ref: "./comment/deleteComment.yaml"

  /categories:
    $ref: "./category/getCategories.yaml"

  /symbols:
    $ref: "./symbol/getSymbols.yaml"
  /symbols/{feedId}:
    $ref: "./symbol/addAndUpdatesymbolToFeed.yaml"
  /symbols/check/{feedId}:
    $ref: "./symbol/checkSymbol.yaml"

  /feeds/temp:
    $ref: "./tempFeed/tempFeed.yaml"

  /feeds:
    $ref: "./feed/getFeedList.yaml"

  /feeds/{feedId}:
    $ref: "./feed/getFeed.yaml"
  /feeds/estimations:
    $ref: "./feed/getEstimations.yaml"

#  /feeds/post:
#    $ref: "./feed/postFeed.yaml"

  /upload:
    $ref: "./uploadFiles/upload.yaml"