openapi: 3.0.2
servers:
  - description: project_review localhost API document
    url: http://localhost:8000
  - description: project_review AWS RDS Test API document
    url: http://3.38.6.179/8000
info:
  version: "1.0.0"
  title: project_review-API
  description: The API for project_review
  contact:
    name: Inchan Song
    url: https://github.com/inchanS
    email: song@inchan.dev
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
paths:
  /users/signup:
    $ref: "./user/signUp.yaml"
  /users/signup/password:
    $ref: "./user/resetPassword.yaml"
  /users/checknickname:
    $ref: "./user/checkNickname.yaml"
  /users/checkemail:
    $ref: "./user/checkEmail.yaml"
  /users/signin:
    $ref: "./user/signIn.yaml"
  /users/userinfo/{userId}:
    $ref: "./user/getUserInfo.yaml"
  /users/userinfo/{userId}/feeds:
    $ref: "./user/getUserInfoFeeds.yaml"
  /users/userinfo/{userId}/comments:
    $ref: "./user/getUserInfoComments.yaml"
  /users/userinfo/{userId}/symbols:
    $ref: "./user/getUserInfoSymbols.yaml"

  /comments:
    $ref: "./comment/index.yaml"
  /comments/{feedId}:
    $ref: "./comment/getComment.yaml"
  /comments/{commentId}:
    $ref: "./comment/deleteComment.yaml"

  /categories:
    $ref: "./category/index.yaml"

  /symbols:
    $ref: "./symbol/getSymbols.yaml"
  /symbols/{feedId}:
    $ref: "./symbol/addAndUpdateSymbolToFeed.yaml"
  /symbols/check/{feedId}:
    $ref: "./symbol/checkSymbol.yaml"

  /feeds/temp:
    $ref: "./tempFeed/index.yaml"

  /feeds/post/:
    $ref: "./feed/index.yaml"

  /feeds/{feedId}:
    $ref: "./feed/getAndDeleteFeed.yaml"

  /feeds/estimations:
    $ref: "./feed/getEstimations.yaml"

  /upload:
    $ref: "./uploadFiles/index.yaml"

  /search:
    $ref: "./search/index.yaml"
  /search/list:
    $ref: "./search/getSearchList.yaml"