openapi: 3.0.0
servers:
  - description: project_review localhost API document
    url: 'http://localhost:8000'
info:
  version: 1.0.0
  title: project_review-API
  description: The API for project_review
  contact:
    name: Inchan Song
    url: 'https://github.com/inchanS'
    email: song@inchan.dev
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
paths:
  /users/signup:
    post:
      tags:
        - User
      summary: 회원가입
      description: 회원가입
      produces:
        - application/json
      requestBody:
        description: 회원가입시 필요한 사용자 정보 객체
        required: true
        content:
          application/json:
            schema:
              $ref: '#/paths/~1users~1signup/components/schemas/User'
      responses:
        '201':
          description: successful operation
          content:
            apllication/json:
              schema:
                $ref: '#/paths/~1users~1signup/components/schemas/Success'
        '500':
          description: Internal server error
          content:
            apllication/json:
              schema:
                $ref: '#/paths/~1users~1signup/components/schemas/Error'
    components:
      schemas:
        User:
          type: object
          properties:
            nickname:
              type: string
              description: The nickname of the user
              example: 블랙팬서
            email:
              type: string
              description: The email of the user
              example: black@test.com
            password:
              type: string
              description: The password of the user
              example: Abcd@1234
        Success:
          type: object
          properties:
            message:
              type: string
              description: 회원가입 성공 메세지
              example: SIGNUP_SUCCESS
        Error:
          type: object
          properties:
            message:
              type: string
              description: 가입 실패시 메세지
              example: (THIS_EMAIL)_IS_MAIL_THAT_ALREADY_EXSITS
  /users/signin:
    post:
      tags:
        - User
      summary: 회원 로그인
      description: 회원 로그인 관련 API
      produces:
        - application/json
      requestBody:
        description: 회원 로그인시 필요한 사용자 정보 객체
        required: true
        content:
          application/json:
            schema:
              $ref: '#/paths/~1users~1signin/components/schemas/User'
      responses:
        '200':
          description: successful operation
          content:
            apllication/json:
              schema:
                $ref: '#/paths/~1users~1signin/components/schemas/Success'
        '500':
          description: Internal server error
          content:
            apllication/json:
              schema:
                $ref: '#/paths/~1users~1signin/components/schemas/Error'
    components:
      schemas:
        User:
          type: object
          properties:
            email:
              type: string
              description: The email of the user
              example: black@test.com
            password:
              type: string
              description: The password of the user
              example: Abcd@1234
        Success:
          type: object
          properties:
            message:
              type: string
              description: 로그인 성공 메세지
              example: SIGNIN_SUCCESS
            result:
              type: object
              description: 로그인 성공시 토큰값
              properties:
                token:
                  type: string
                  description: 토큰값
                  example: 'token: ''eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImlhdCI6MTY3ODEyOTY0OX0.eyNOFEZt5xPSakzy4FyGqub9heSZA5FtOZGtWyTI4vg'''
        Error:
          type: object
          properties:
            message:
              type: string
              description: 로그인 실패시 메세지
              example: (THIS_EMAIL)_IS_NOT_FOUND
  /users/checknickname:
    get:
      tags:
        - User
      summary: 회원가입시 닉네임 중복체크
      description: 회원가입시 닉네임 중복체크
      produces:
        - application/json
      parameters:
        - name: nickname
          in: query
          description: 중복체크할 닉네임
          required: true
          type: string
          example: 'http://localhost:8000/users/checknickname?nickname=블랙팬서'
      responses:
        '200':
          description: successful operation
          content:
            apllication/json:
              schema:
                $ref: '#/paths/~1users~1checknickname/components/schemas/Success'
        '500':
          description: Internal server error
          content:
            apllication/json:
              schema:
                $ref: '#/paths/~1users~1checknickname/components/schemas/Error'
    components:
      schemas:
        Success:
          type: object
          properties:
            message:
              type: string
              description: 닉네임 중복체크 성공 메세지
              example: AVAILABLE_NICKNAME
        Error:
          type: object
          properties:
            message:
              type: string
              description: 닉네임 중복체크 실패 메세지
              example: (THIS_EMAIL)_IS_NICKNAME_THAT_ALREADY_EXSITS
  /users/checkemail:
    get:
      tags:
        - User
      summary: 회원가입시 이메일 중복체크
      description: 회원가입시 이메일 중복체크
      produces:
        - application/json
      parameters:
        - name: email
          in: query
          description: 중복체크할 이메일
          required: true
          type: string
          example: 'http://localhost:8000/users/checkemail?email=test123'
      responses:
        '200':
          description: successful operation
          content:
            apllication/json:
              schema:
                $ref: '#/paths/~1users~1checkemail/components/schemas/Success'
        '500':
          description: Internal server error
          content:
            apllication/json:
              schema:
                $ref: '#/paths/~1users~1checkemail/components/schemas/Error'
    components:
      schemas:
        Success:
          type: object
          properties:
            message:
              type: string
              description: 이메일 중복체크 성공 메세지
              example: AVAILABLE_EMAIL
        Error:
          type: object
          properties:
            message:
              type: string
              description: 이메일 중복체크 실패 메세지
              example: (THIS_EMAIL)_IS_EMAIL_THAT_ALREADY_EXSITS
  /users/getme:
    get:
      tags:
        - User
      summary: 로그인한 유저의 모든 정보 보기
      description: '로그인한 유저의 ID, 가입일, 닉네임, 이메일과 게시글 목록, 댓글 목록을 반환합니다.'
      produces:
        - application/json
      security:
        - BearerAuth: []
      responses:
        '200':
          description: successful operation
          content:
            apllication/json:
              schema:
                $ref: '#/paths/~1users~1getme/components/schemas/Success'
        '500':
          description: Internal server error
          content:
            apllication/json:
              schema:
                $ref: '#/paths/~1users~1getme/components/schemas/Error'
    components:
      schemas:
        Success:
          type: object
          properties:
            message:
              type: string
              description: 닉네임 중복체크 성공 메세지
              example: AVAILABLE_NICKNAME
        Error:
          type: object
          properties:
            message:
              type: string
              description: 닉네임 중복체크 실패 메세지
              example: (THIS_EMAIL)_IS_NICKNAME_THAT_ALREADY_EXSITS
